import React,{useMemo,useState} from 'react';
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, Columns3, FileText, RotateCcw, WrapText } from 'lucide-react';
import Modal from './Modal';
const allCols=[['document_number','رقم الوثيقة',150],['document_date','تاريخ الوثيقة',120],['owner_name','اسم المالك',210],['property_type','نوع العقار',130],['property_area','مساحة العقار',115],['plot_number','رقم القطعة',95],['plan_number','رقم المخطط',110],['district','الحي',150],['city','المدينة',130],['held_by','الصك لدى',150]];
const defaults=Object.fromEntries(allCols.map(([k,,w])=>[k,w]));
export default function DeedsTable({result,selectedId,onSelect,onPage,pageSize,onPageSize}){
 const {items=[],total=0,page=1,pages=1}=result||{};const [settingsOpen,setSettingsOpen]=useState(false);const [wrap,setWrap]=useState(()=>localStorage.getItem('deed-table-wrap')==='1');const [hidden,setHidden]=useState(()=>{try{return JSON.parse(localStorage.getItem('deed-table-hidden')||'[]')}catch{return[]}});const [widths,setWidths]=useState(()=>{try{return{...defaults,...JSON.parse(localStorage.getItem('deed-table-widths')||'{}')}}catch{return defaults}});
 const cols=useMemo(()=>allCols.filter(([k])=>!hidden.includes(k)),[hidden]);const pageNumbers=[];for(let p=Math.max(1,page-2);p<=Math.min(pages,page+2);p++)pageNumbers.push(p);
 function startResize(e,key){e.preventDefault();const startX=e.clientX,startW=widths[key]||120;const move=ev=>{const w=Math.max(70,startW-(ev.clientX-startX));setWidths(x=>{const n={...x,[key]:w};localStorage.setItem('deed-table-widths',JSON.stringify(n));return n})};const up=()=>{window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up)}
 function toggle(k){setHidden(h=>{const n=h.includes(k)?h.filter(x=>x!==k):[...h,k];localStorage.setItem('deed-table-hidden',JSON.stringify(n));return n})}
 function toggleWrap(){setWrap(v=>{localStorage.setItem('deed-table-wrap',v?'0':'1');return!v})}
 function reset(){setWidths(defaults);setHidden([]);localStorage.removeItem('deed-table-widths');localStorage.removeItem('deed-table-hidden')}
 return <section className="panel table-panel"><div className="table-head"><div><h3>الصكوك والعقارات</h3><span>{total} نتيجة</span></div><div className="table-tools"><button className={`mini-tool ${wrap?'active':''}`} onClick={toggleWrap}><WrapText size={15}/>التفاف النص</button><button className="mini-tool" onClick={()=>setSettingsOpen(true)}><Columns3 size={15}/>الأعمدة</button></div></div>
  <div className={`table-scroll ${wrap?'wrap-cells':''}`}><table style={{minWidth:48+cols.reduce((sum,[k])=>sum+(widths[k]||120),0)}}><colgroup><col style={{width:48}}/>{cols.map(([k])=><col key={k} style={{width:widths[k]}}/>)}</colgroup><thead><tr><th className="serial">م</th>{cols.map(([k,l])=><th key={k}>{l}<i className="col-resizer" onMouseDown={e=>startResize(e,k)}/></th>)}</tr></thead><tbody>{items.map((r,i)=><tr key={r.id} className={selectedId===r.id?'selected':''} onClick={()=>onSelect(r.id)}><td className="serial">{(page-1)*pageSize+i+1}</td>{cols.map(([k])=><td key={k} title={r[k]||''}>{r[k]||'—'}</td>)}</tr>)}{!items.length&&<tr><td className="empty-cell" colSpan={cols.length+1}><div><FileText size={32}/><b>لا توجد صكوك</b><span>أضف أول صك أو غيّر معايير البحث.</span></div></td></tr>}</tbody></table></div>
  <div className="pager"><div className="page-size"><span>عرض</span><select value={pageSize} onChange={e=>onPageSize(Number(e.target.value))}><option>8</option><option>12</option><option>20</option><option>50</option></select><span>لكل صفحة</span></div><div className="page-status">صفحة {page} من {pages}</div><div className="page-buttons"><button disabled={page===1} onClick={()=>onPage(1)}><ChevronsRight size={17}/></button><button disabled={page===1} onClick={()=>onPage(page-1)}><ChevronRight size={17}/></button>{pageNumbers.map(p=><button className={p===page?'active':''} key={p} onClick={()=>onPage(p)}>{p}</button>)}<button disabled={page===pages} onClick={()=>onPage(page+1)}><ChevronLeft size={17}/></button><button disabled={page===pages} onClick={()=>onPage(pages)}><ChevronsLeft size={17}/></button></div></div>
  <Modal open={settingsOpen} title="التحكم في أعمدة الجدول" onClose={()=>setSettingsOpen(false)} width={620}><div className="column-settings">{allCols.map(([k,l])=><label key={k}><input type="checkbox" checked={!hidden.includes(k)} onChange={()=>toggle(k)}/><span>{l}</span></label>)}<button className="btn secondary" onClick={reset}><RotateCcw size={17}/>إعادة الضبط</button></div></Modal>
 </section>
}
