import React,{useEffect,useState} from 'react';
import { Eye, FileImage, ImagePlus, Trash2, FileText, Building2, ExternalLink, NotebookPen, Save } from 'lucide-react';
import { api } from '../lib/api';
import Modal from './Modal';
export default function PreviewPanel({deed,onAddAttachment,onOpenAttachment,onPreviewAttachment,onDeleteAttachment,onSaveAttachmentNotes}){
 const [previews,setPreviews]=useState({});
 const [contextMenu,setContextMenu]=useState(null),[notesAttachment,setNotesAttachment]=useState(null),[notes,setNotes]=useState('');
 useEffect(()=>{let alive=true;async function load(){if(!deed?.attachments?.length){setPreviews({});return}const pairs=await Promise.all(deed.attachments.slice(0,6).filter(a=>a.mime_group==='image').map(async a=>[a.id,await api.getAttachmentPreview(a.id)]));if(alive)setPreviews(Object.fromEntries(pairs))}load();return()=>{alive=false}},[deed?.id,deed?.attachments?.length]);
 useEffect(()=>{if(!contextMenu)return;const close=()=>setContextMenu(null);window.addEventListener('click',close);window.addEventListener('scroll',close,true);window.addEventListener('blur',close);return()=>{window.removeEventListener('click',close);window.removeEventListener('scroll',close,true);window.removeEventListener('blur',close)}},[contextMenu]);
 function openContextMenu(event,attachment){event.preventDefault();event.stopPropagation();const width=190,height=52;setContextMenu({attachment,x:Math.min(event.clientX,window.innerWidth-width-8),y:Math.min(event.clientY,window.innerHeight-height-8)})}
 function openNotes(attachment){setContextMenu(null);setNotesAttachment(attachment);setNotes(attachment.notes||'')}
 async function saveNotes(){await onSaveAttachmentNotes(notesAttachment.id,notes);setNotesAttachment(null)}
 if(!deed)return <section className="panel preview-panel empty-preview"><Building2 size={38}/><h3>اختر صكًا للمعاينة</h3><p>اضغط على أي صف في الجدول لعرض بيانات الصك ومرفقاته هنا.</p></section>;
 const info=[['رقم الوثيقة',deed.document_number],['تاريخ الوثيقة',deed.document_date],['اسم المالك',deed.owner_name],['نوع العقار',deed.property_type],['المساحة',deed.property_area],['رقم القطعة',deed.plot_number],['رقم المخطط',deed.plan_number],['الحي',deed.district],['المدينة',deed.city],['الصك لدى',deed.held_by]];
 const firstImage=deed.attachments?.find(a=>previews[a.id]);
 return <section className="panel preview-panel"><div className="panel-title"><div><FileText size={20}/><h3>معاينة الصك</h3></div><span className="badge">{deed.attachments?.length||0} مرفق</span></div>
  <div className="document-hero">{firstImage?<img className="hero-image clickable" onClick={()=>onPreviewAttachment(firstImage)} src={previews[firstImage.id]} alt="معاينة الصك"/>:<div className="paper"><FileText size={38}/><b>{deed.document_number}</b><span>{deed.owner_name}</span></div>}</div>
  <div className="attachments-row">{(deed.attachments||[]).map(a=><div key={a.id} className={`attachment-thumb ${a.notes?'has-attachment-notes':''}`} title={a.notes?'':a.original_name} onContextMenu={event=>openContextMenu(event,a)}>{previews[a.id]?<img src={previews[a.id]} alt=""/>:a.mime_group==='image'?<FileImage size={24}/>:<FileText size={24}/>}<span>{a.original_name}</span>{a.notes&&<><i className="attachment-note-mark"><NotebookPen size={11}/></i><div className="attachment-note-tooltip"><b>بيانات المرفق</b><p>{a.notes}</p></div></>}<div className="thumb-actions"><button title="معاينة" onClick={()=>onPreviewAttachment(a)}><Eye size={12}/></button><button title="فتح" onClick={()=>onOpenAttachment(a.id)}><ExternalLink size={12}/></button><button className="del" title="حذف" onClick={()=>onDeleteAttachment(a)}><Trash2 size={12}/></button></div></div>)}{!deed.attachments?.length&&<div className="no-attachments">لا توجد مرفقات بعد</div>}</div>
  <button className="btn primary full-btn" onClick={onAddAttachment}><ImagePlus size={17}/>إضافة صور / PDF</button>
  <div className="info-list">{info.map(([k,v])=><div className="info-row" key={k}><span>{k}</span><b title={v||''}>{v||'—'}</b></div>)}</div>{deed.notes&&<div className="notes-box"><span>ملاحظات</span><p>{deed.notes}</p></div>}
  {contextMenu&&<div className="attachment-context-menu" style={{left:contextMenu.x,top:contextMenu.y}} onClick={event=>event.stopPropagation()}><button onClick={()=>openNotes(contextMenu.attachment)}><NotebookPen size={16}/><span>{contextMenu.attachment.notes?'تعديل البيانات':'إضافة بيانات'}</span></button></div>}
  <Modal open={!!notesAttachment} title="بيانات المرفق" onClose={()=>setNotesAttachment(null)} width={540}><div className="attachment-notes-form"><div className="attachment-notes-file"><FileText size={17}/><span>{notesAttachment?.original_name}</span></div><label><span>ملاحظات خاصة بالمرفق</span><textarea autoFocus value={notes} onChange={event=>setNotes(event.target.value)} placeholder="اكتب أي بيانات أو ملاحظات تساعدك على معرفة محتوى المرفق..." rows={6}/></label><div className="modal-actions"><button className="btn secondary" onClick={()=>setNotesAttachment(null)}>إلغاء</button><button className="btn primary" onClick={saveNotes}><Save size={17}/>حفظ البيانات</button></div></div></Modal>
 </section>
}
